<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bam.base\bam.base\bam.base.csproj" />
    <ProjectReference Include="..\..\bam.commandline\bam.commandline\bam.commandline.csproj" />
    <ProjectReference Include="..\..\bam.configuration\bam.configuration\bam.configuration.csproj" />
    <ProjectReference Include="..\..\bam.console\bam.console\bam.console.csproj" />
    <ProjectReference Include="..\..\bam.data.repositories\bam.data.repositories\bam.data.repositories.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data\bam.data.csproj" />
    <ProjectReference Include="..\..\bam.logging\bam.logging\bam.logging.csproj" />
    <ProjectReference Include="..\..\bam.shell\bam.shell\bam.shell.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CommandLineTestTool.cs" />
    <Compile Remove="Integration\IntegrationTestRunnerObsolete.cs" />
    <Compile Remove="Obsolete\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Obsolete\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Obsolete\**" />
  </ItemGroup>

</Project>
